server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: ${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:${server.port}/eureka}
logging:
  level:
    web: DEBUG