server:
  port: 8761

spring:
  application:
    name: '@project.name@'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${SERVICE_REGISTRY}

logging:
  level:
    web: DEBUG